// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechAtHome.Data;

namespace TechAtHome.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20200412095344_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechAtHome.Data.Models.CategoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Db_Category");
                });

            modelBuilder.Entity("TechAtHome.Data.Models.GoodModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryNum")
                        .HasColumnType("int");

                    b.Property<int?>("GoodModel_ListID")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavour")
                        .HasColumnType("bit");

                    b.Property<string>("LongSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortSpec")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GoodModel_ListID");

                    b.ToTable("Db_Good");
                });

            modelBuilder.Entity("TechAtHome.Data.Models.ShopCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GoodModelCartID")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceCart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShopCartModelId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodModelCartID");

                    b.ToTable("Db_ShopCartItem");
                });

            modelBuilder.Entity("TechAtHome.Data.Models.GoodModel", b =>
                {
                    b.HasOne("TechAtHome.Data.Models.CategoryModel", "GoodModel_List")
                        .WithMany("CategoryModel_List")
                        .HasForeignKey("GoodModel_ListID");
                });

            modelBuilder.Entity("TechAtHome.Data.Models.ShopCartItem", b =>
                {
                    b.HasOne("TechAtHome.Data.Models.GoodModel", "GoodModelCart")
                        .WithMany()
                        .HasForeignKey("GoodModelCartID");
                });
#pragma warning restore 612, 618
        }
    }
}
